name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的功能建议！请详细描述你的想法。
        Thanks for suggesting a new feature!

  - type: textarea
    id: description
    attributes:
      label: 功能描述 / Feature Description
      description: 简要描述你希望添加的功能
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景 / Use Case
      description: 这个功能解决什么问题？在什么场景下会用到？
      placeholder: 当我需要...的时候，这个功能会很有用
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议实现方式 / Proposed Solution
      description: 如果你有实现思路，请描述
      placeholder: 可以通过...来实现

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives Considered
      description: 你考虑过其他替代方案吗？
      placeholder: 也可以考虑...

  - type: textarea
    id: additional
    attributes:
      label: 其他信息 / Additional Context
      description: 任何其他相关信息，如截图、参考链接等
